[project]
name = "social_media_api"
version = "0.1.0"
dependencies = [
    "psycopg2-binary==2.9.11",
]

[tool.uv]
# This line is the magic fix: it tells Vercel's builder
# NEVER to try and build psycopg2 from source code.
no-build = ["psycopg2", "psycopg2-binary"]